services:
  mysqldb:
    image: 'mysql:latest'
    container_name: "mysqldb"
    environment:
      - MYSQL_ROOT_PASSWORD=root 
      - MYSQL_DATABASE=mydata 
    volumes:
      - db_data:/var/lib/mysql
      - ./server.txt:/myapp/server.txt
    networks:
      - My-Net
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 20s
      retries: 20

  mypythonapp:
    build: ./
    container_name: mypyapp 
    networks:
      - My-Net
    depends_on:
      mysqldb:
        condition: service_healthy
    stdin_open: true
    tty: true

networks:
  My-Net:

volumes:
  db_data:
